WARNING: /home/nico/Desktop/tLeng2016(posta)/tleng2016/parser_rules.py:657: Function p_valoresBool redefined. Previously defined on line 648
WARNING: /home/nico/Desktop/tLeng2016(posta)/tleng2016/parser_rules.py:663: Function p_valoresBool redefined. Previously defined on line 648
Generating LALR tables
Traceback (most recent call last):
  File "parser.py", line 50, in <module>
    ast = parser.parse(text, lexer,debug=0)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 1106, in parseopt_notrack
    p.callable(pslice)
  File "/home/nico/Desktop/tLeng2016(posta)/tleng2016/parser_rules.py", line 278, in p_valores
    subexpressions[0]["type"] = subexpressions[1]["type"] 
KeyError: 'type'
Traceback (most recent call last):
  File "parser.py", line 50, in <module>
    ast = parser.parse(text, lexer,debug=0)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 1106, in parseopt_notrack
    p.callable(pslice)
  File "/home/nico/Desktop/tLeng2016(posta)/tleng2016/parser_rules.py", line 509, in p_varAsig
    nombreVar = subexpressions[1]["var"]
KeyError: 'var'
Traceback (most recent call last):
  File "parser.py", line 50, in <module>
    ast = parser.parse(text, lexer,debug=0)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/nico/Desktop/tLeng2016(posta)/tleng2016/parser_rules.py", line 771, in p_error
    raise Exception(message)
Exception: [Syntax error]
type:AND
value:{'var': 'AND', 'type': 'noType', 'value': 'AND'}
line:3
position:27
Traceback (most recent call last):
  File "parser.py", line 50, in <module>
    ast = parser.parse(text, lexer,debug=0)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/nico/Desktop/tLeng2016(posta)/tleng2016/parser_rules.py", line 771, in p_error
    raise Exception(message)
Exception: [Syntax error]
type:?
value:?
line:18
position:162
Traceback (most recent call last):
  File "parser.py", line 50, in <module>
    ast = parser.parse(text, lexer,debug=0)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/nico/Desktop/tLeng2016(posta)/tleng2016/parser_rules.py", line 771, in p_error
    raise Exception(message)
Exception: [Syntax error]
type:?
value:?
line:19
position:314
Traceback (most recent call last):
  File "parser.py", line 50, in <module>
    ast = parser.parse(text, lexer,debug=0)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/nico/Desktop/tLeng2016(posta)/tleng2016/parser_rules.py", line 771, in p_error
    raise Exception(message)
Exception: [Syntax error]
type:BOOL
value:{'type': 'bool', 'value': 'true'}
line:1
position:4
Traceback (most recent call last):
  File "parser.py", line 50, in <module>
    ast = parser.parse(text, lexer,debug=0)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 1106, in parseopt_notrack
    p.callable(pslice)
  File "/home/nico/Desktop/tLeng2016(posta)/tleng2016/parser_rules.py", line 583, in p_eMat2
    subexpressions[0]["type"] = subexpressions[2]["type"]
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "parser.py", line 50, in <module>
    ast = parser.parse(text, lexer,debug=0)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 1106, in parseopt_notrack
    p.callable(pslice)
  File "/home/nico/Desktop/tLeng2016(posta)/tleng2016/parser_rules.py", line 278, in p_valores
    subexpressions[0]["type"] = subexpressions[1]["type"] 
KeyError: 'type'
Traceback (most recent call last):
  File "parser.py", line 50, in <module>
    ast = parser.parse(text, lexer,debug=0)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/nico/Desktop/tLeng2016(posta)/tleng2016/parser_rules.py", line 771, in p_error
    raise Exception(message)
Exception: [Syntax error]
type:BOOL
value:{'type': 'bool', 'value': 'false'}
line:12
position:103
